# Generated by Django 4.1.4 on 2023-04-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedbackdata',
            new_name='contactpage',
        ),
    ]
