# Generated by Django 4.1.4 on 2023-04-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0003_rename_feedbackdata_contactpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactpage',
            new_name='feedbackdata',
        ),
    ]
