# Generated by Django 4.1.4 on 2023-04-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0004_rename_contactpage_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ratings', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
